# Copyright (C) 2017-2018  Andrew Gunnerson <andrewgunnerson@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM fedora_29_androidsdk-2

# Install Android NDK
ARG ANDROID_NDK_VERSION=r18b
ARG ANDROID_NDK_CHECKSUM=500679655da3a86aecf67007e8ab230ea9b4dd7b
ENV ANDROID_NDK_HOME /opt/android-ndk
ENV ANDROID_NDK ${ANDROID_NDK_HOME}


# Set up path
ENV PATH ${PATH}:${ANDROID_NDK_HOME}

# Volumes
ENV BUILDER_HOME /builder
RUN mkdir -m 0700 ${BUILDER_HOME}
WORKDIR ${BUILDER_HOME}

# Entrypoint
ADD entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
